# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.17.1/www/static/schema.json
version: 2

before:
  hooks:
    - go mod download
    - go generate ./...
    - go test -v -cover ./...
builds:
  - binary: ply
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X ply/cmd.buildDate={{.Date}} -X ply/cmd.version={{.Version}}
#archives:
#  - replacements:
#      darwin: Darwin
#      linux: Linux
#      windows: Windows
#      386: i386
#      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  disable: true
