# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class CoPilot < Formula
  desc "Co-pilot is a developer tool for automating common tasks on a spring boot project."
  homepage "https://co-pilot-cli.github.io/"
  version "0.4.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.8/co-pilot_0.4.8_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5eba66b3a88940d03db78fef7d708ff0df7900bbff89d9ae362160b06244f951"

      def install
        bin.install "co-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.8/co-pilot_0.4.8_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fac17532e8ccd64ec7f1cbe417da7b75bd76bf0f9f2ae0954a5beecc226c8b1c"

      def install
        bin.install "co-pilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.8/co-pilot_0.4.8_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4e34a04090e014014230f2bd189fa82dc55c144715006fc56092207d9f636ce3"

      def install
        bin.install "co-pilot"
      end
    end
  end
end
