# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class CoPilot < Formula
  desc "Co-pilot is a developer tool for automating common tasks on a spring boot project."
  homepage "https://co-pilot-cli.github.io/"
  version "0.4.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.13/co-pilot_0.4.13_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "72e0d28413033c8b82d072664bfec12878b6d0b4dd61bd1778e4a991686af7e0"

      def install
        bin.install "co-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.13/co-pilot_0.4.13_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bc64c04f20af8537eda8c1701272dc08129550ca1795f5dab64b83141731e630"

      def install
        bin.install "co-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.13/co-pilot_0.4.13_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b5de23491267aa2b933bf9747f5cbfe231adebe23381460207ad23e6efcaca1c"

      def install
        bin.install "co-pilot"
      end
    end
  end
end
