# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class CoPilot < Formula
  desc "Co-pilot is a developer tool for automating common tasks on a spring boot project."
  homepage "https://co-pilot-cli.github.io/"
  version "0.4.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.12/co-pilot_0.4.12_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6b94e3c53bbe6808c0d07e86c78ebe817a68f808789caf94385ac6ec89483184"

      def install
        bin.install "co-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.12/co-pilot_0.4.12_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3808f0661d0d9578749ace320ecade12a4905506c699629ceff8e4c758fce8f1"

      def install
        bin.install "co-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/co-pilot-cli/co-pilot/releases/download/v0.4.12/co-pilot_0.4.12_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "08cf45bd869213b37238ad9f644860ce9092bfad626e45a319414ad708bdbce3"

      def install
        bin.install "co-pilot"
      end
    end
  end
end
